### ISSUE TITLE
libvips supports pdf, gif and svg formats from version 8.4

### ISSUE THREAD

**Issue by h2non** [greut/iiif#4]
Just to let you know that `libvips` supports from version 8.4 additional image output format, if compiled against required library bindings.

`bimg` and `imaginary` supports that too in recent versions.

BTW... this is an interesting project. I always wished some standard API for image processing. 
I will consider supporting IIIF in future `imaginary` major releases, or at least take some inspiration for a simpler, more predictable API design.

**Comment by greut** [comment]
@h2non Hey, thanks for the ping. `imaginary` looks very interesting indeed. The good part of IIIF is that you can easily plug viewers like leaflet-iiif.
